apiVersion: v1
kind: Service
metadata:
  name: hello-node-master
  labels:
    app: hello-node
    role: master
    tier: backend
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: hello-node
    role: master
    tier: backend